services:
  discord-bot:
    build: .
    env_file: .env.example
    environment:
      AUTOSTREAM_NODE_CONFIG: /etc/autostream-discord-bot/config.yml
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yml:/etc/autostream-discord-bot/config.yml:ro
