services:
  discord-bot:
    image: ${AUTOSTREAM_IMAGE_REGISTRY:-ghcr.io/kome-lab/autostream-docker}/discord-bot:${AUTOSTREAM_DOCKER_VERSION:-latest}
    restart: unless-stopped
    env_file: .env
    ports: !override
      - "127.0.0.1:${AUTOSTREAM_DISCORD_BOT_PORT:-8083}:${AUTOSTREAM_DISCORD_BOT_CONTAINER_PORT:-8080}"
